app: "mikudos-service-ts"
consumer_group: "mikudos-service-ts"
brokers:
  - "127.0.0.1:9092"
mongodb: "mongodb+srv://qiushanyu666:qiushanyu666@cluster0-exxbz.mongodb.net/yue?retryWrites=true"
port: 50051
interServiceClients:

  ali_oss:
    name: "127.0.0.1"
    port: "50051"
  rbac:
    name: "127.0.0.1"
    port: "50052"
  users:
    name: "127.0.0.1"
    port: "50053"
